### ISSUE TITLE
Several warnings when importing in Unity 2017.3p4

### ISSUE THREAD

**Issue by ratkingsminion** [Unity-Technologies/SimpleAnimation#12]
See title. These are the warnings I get every time the project compiles:

> `AnimationProxy.animation' hides inherited member `UnityEngine.Component.animation'. Use the new keyword if hiding was intended
warning CS0108: Assets/SimpleAnimationComponent/Tests/AnimationProxy.cs(74,23)

> `AnimationProxy.gameObject' hides inherited member `UnityEngine.Component.gameObject'. Use the new keyword if hiding was intended
warning CS0108: Assets/SimpleAnimationComponent/Tests/AnimationProxy.cs(156,23)

> `SimpleAnimationProxy.gameObject' hides inherited member `UnityEngine.Component.gameObject'. Use the new keyword if hiding was intended
warning CS0108: Assets/SimpleAnimationComponent/Tests/SimpleAnimationProxy.cs(131,23)

> The variable `defaultState' is assigned but its value is never used
warning CS0219: Assets/SimpleAnimationComponent/SimpleAnimation_impl.cs(348,17)

> `UnityEngine.Playables.PlayableExtensions.SetPlayState<UnityEngine.Playables.Playable>(this UnityEngine.Playables.Playable, UnityEngine.Playables.PlayState)' is obsolete: `SetPlayState() has been deprecated. Use Play(), Pause() or SetDelay() instead'
warning CS0618: Assets/SimpleAnimationComponent/SimpleAnimationPlayable.cs(117,31)

> `UnityEngine.Playables.PlayableExtensions.SetPlayState<UnityEngine.Playables.Playable>(this UnityEngine.Playables.Playable, UnityEngine.Playables.PlayState)' is obsolete: `SetPlayState() has been deprecated. Use Play(), Pause() or SetDelay() instead'
warning CS0618: Assets/SimpleAnimationComponent/SimpleAnimationPlayable.cs(505,38)

> `UnityEngine.Playables.PlayableExtensions.SetPlayState<UnityEngine.Playables.Playable>(this UnityEngine.Playables.Playable, UnityEngine.Playables.PlayState)' is obsolete: `SetPlayState() has been deprecated. Use Play(), Pause() or SetDelay() instead'
warning CS0618: Assets/SimpleAnimationComponent/SimpleAnimationPlayable.cs(542,32)

> Field `SimpleAnimationPlayable.StateInfo.speed' is never assigned to, and will always have its default value `0'
warning CS0649: Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs(286,22)

> The private field `SimpleAnimationEditor.m_AnimationsExpanded' is assigned but its value is never used
warning CS0414: Assets/SimpleAnimationComponent/Editor/SimpleAnimationEditor.cs(25,10)

**Comment by davidg-unity** [comment]
Fixed in https://github.com/Unity-Technologies/SimpleAnimation/pull/17 
Merged to master.

All the warnings that appeared at compile time were fixed for 2017.3.0f1
