### ISSUE TITLE
A state's normalized time should be independent of its speed

### ISSUE THREAD

**Issue by ifayad** [Unity-Technologies/SimpleAnimation#15]
Hello @davidg-unity, I noticed that when getting a state's normalized time, the reported value is dependent of the speed at which the current state is playing at. At first, it seemed logical, however, this proves problematic when setting the speed to 0 for example. In that case, the normalized time will report 0 even if I am in the middle of the clip. More issues surfaced when I wanted to set the normalized time when the state speed was zero. If, for example, I set it to 0.5f which should jump to the middle of the animation, the system will factor in the speed  and set it to infinity. I think that the component should not factor in the speed when reporting the normalized time. Here's a rough fix, which is working for my case:

class: SimpleAnimationPlayable_States.cs
line: ~469

 '-' : Removed line(s)
 '+': Added line

```
        public float GetStateLength(int index)
        {
            AnimationClip clip = m_States[index].clip;
            if (clip == null)
                return 0f;
        -    float speed = (float)m_States[index].playable.GetSpeed();
        -   if (m_States[index].playable.GetSpeed() == 0f)
        -        return Mathf.Infinity;

        -    return clip.length/speed;
        +    return clip.length;
        }
```

**Comment by davidg-unity** [comment]
Fixed in master branch.

Thanks again for the reports
