### ISSUE TITLE
Setting State weight outside of blend or crossfade have no effect (Possible fix suggested)

### ISSUE THREAD

**Issue by ifayad** [Unity-Technologies/SimpleAnimation#16]
If you tried the component long enough, you will notice that if you set a state's weight to a new value after it has been initialized, the new weight will have no effect, except when used with blend/cross fade. The issue is that the weight is taken into account in the state, however, it's not flagged to be updated once the SimpleAnimationPlayable is updating the inputs to the mixer. Below is fix for that issue. The fix also takes into account the normalization of the weights vector before sending it to the mixer (Playables don't play nice when sum of weights is > 1).

Modified class: private class StateInfo in the file "SimpleAnimationPlayable_States.cs"
Line: ~300 (midway through)

In this class I added a float value called:
`public float suggestedWeight;`

You can add it anywhere, however, for consistency I placed it after targetWeight;

This will be useful when we adjust the weights so their sum is equal to one. In simple terms, the user "suggests" a weight of a state and the code will adjust it accordingly. Imagine only one state is playing, if we set the weight to 0.5f, the weights in the mixer will be 0.5 (you don't want that). The actual weight will be set to 1 instead (and we preserve the suggested weight in case we played another state). This is the behavior of the legacy animation component. Another example, if we have two states, one with a weight of 1 and the other 0.5, their sum is 1.5 (You also don't want that in the mixer, unless you want your character to morph into a chicken). Therefore, the suggested weights are 0.5 and 1, however, the updated weights are respectively ~0.66 and ~0.33.

To change that, I modified the class StateHandle also in the same file.
locate the weight property and add the following code to the set accessor:

```
set
            {
                if (!IsValid())
                    throw new System.InvalidOperationException("This StateHandle is not valid");
                if (value < 0)
                    throw new System.ArgumentException("Weights cannot be negative");

                    //Added to enforce weight change down the line
                    m_Parent.m_States[m_Index].weight = value;
                    m_Parent.m_States[m_Index].suggestedWeight = value;
                    //Flagged for weight change when we update the mixer
                    m_Parent.m_States[m_Index].weightDirty = true;
                    // Sum of all state weights
                    float sumWeights = 0;

                    //In this loop we calculate the sum of all weights for all the states
                    for (int i = 0; i < m_Parent.m_States.Count; i++)
                    {
                      if(m_Parent.m_States[i].enabled)
                      sumWeights += m_Parent.m_States[i].suggestedWeight;
                    }

                    // If the sum of all weights is equal to 0, then set the default state's weight to 1
                   // This is needed if the mixer has a sum of weights of 0, because the character will be in a fetus position 
                    if (Mathf.Approximately(sumWeights, 0f))
                    {
                        if(!m_Parent.m_States[0].enabled)
                        m_Parent.m_States[0].enabled = true;
                        m_Parent.m_States[0].weight = 1;
                        m_Parent.m_States[0].weightDirty = true;
                    }
                    // Else, make sum weights = 1
                    else
                    {
                        for (int i = 0; i < m_Parent.m_States.Count; i++)
                        {
                            m_Parent.m_States[i].weight = m_Parent.m_States[i].suggestedWeight / sumWeights;
                            m_Parent.m_States[i].weightDirty = true;
                        }
                    }

            }
```

The chicken animation mentioned above when weights > 1.

![bakaak](https://user-images.githubusercontent.com/15981533/36271497-73293852-1287-11e8-916f-70265712a9b7.png)

**Comment by M-Gascoin** [comment]
I can't thank you enough @ifayad. I was facing the same issue and couldn't fix it. I followed your suggestions and they seem to be working with no bugs so far. we'll see how they hold up. +1 for the chicken. I had a different thing when toying with the playables a while back lol.

**Comment by davidg-unity** [comment]
[This](https://github.com/Unity-Technologies/SimpleAnimation/pull/19) pull request should address your issues.

As far as weight normalization goes, there are quite a few advantages to non-normalized weights:

- You can drive independent blend shapes (Play a wink animation and a smile animation simultaneously, both at 100%)
- You can fade out States without playing an empty State

But the main goal for this component is to mimic Animation Component functionality, so it is now normalizing, just like the Animation Component. If you ever want to do blend shapes, you can always disable the normalization directly in the code.

Thanks for the issue report.
