### ISSUE TITLE
Animation Events are triggered immediately at the start of the animation after the first play

### ISSUE THREAD

**Issue by SilentSin** [Unity-Technologies/SimpleAnimation#21]
I made a simple script that plays an animation while you hold space, then returns to the default:

    public AnimationClip clip;

    private SimpleAnimation Controller { get { return GetComponent<SimpleAnimation>(); } }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            Controller.Play(clip.name);
        }
        if (Input.GetKeyUp(KeyCode.Space))
        {
            Controller.Play(Controller.clip.name);
        }
    }

    private void MyEvent()
    {
        Debug.Log("MyEvent");
    }

It plays the animation and triggers its animation event as expected, but each time I play the animation after the first, it logs "MyEvent" immediately at the start of the animation as well as at the correct time.

In `SimpleAnimationPlayable.OnGraphStop` and `SimpleAnimationPlayable.UpdateStates` I found that it calls `input.SetTime(0f);` twice in a row, and changing `StateManagement.StopState` to call it twice does fix the issue, but it seems like a hacky workaround and this would mean that 3 out of the 4 places the method is used are double calls.

Interestingly, the `playable.GetPreviousTime` extension method returns the same value before and after any SetTime calls, so the system is obviously not using that value to determine when to trigger the events.

**Comment by davidg-unity** [comment]
Thanks for reporting this issue.

> changing StateManagement.StopState to call it twice does fix the issue, but it seems like a hacky workaround

I agree, but it's the correct one, at least for the time being.

Playables are currently missing a clear distinction between SetTime and "Teleport Time".

Right now, if you call SetTime twice, the first call updates the clip's deltaTime (in this specific case, the deltaTime would be clipStartTime-clipEndTime, or probably -clip.length if the clip had played entirely), then the second resets the deltaTime to zero (clipStartTime - clipStartTime). Events are then evaluated based on the elapsed deltaTime between frames.

So unless SetTime is called twice (in Stop or in Start), then every event in the clip would be played backward, potentially multiple times if the clip had looped before being stopped.

Once this gets properly addressed in Unity, then this can be replaced by a proper "ResetTime" or something along those lines.

**Comment by davidg-unity** [comment]
[This](https://github.com/Unity-Technologies/SimpleAnimation/pull/22) pull request should address your issue.

Investigating this, I also found a discrepancy between using State.time in SimpleAnimation and Animation; the new time would be considered like a deltaTime in SimpleAnimation, and would be considered like a "ResetTime" in Animation.

Now, both behaviours are aligned, and events in-between last frame and the new SetTime time are not fired.

**Comment by SilentSin** [comment]
Should I report this as a Unity bug?

**Comment by davidg-unity** [comment]
You can. Especially if you're interested in knowing when it's fixed.

But we're already aware of it. We're mostly waiting for more usage patterns to emerge as more people use and create playables, so we can make an API that works for everyone.

There's still very few people who use playables outside of Timeline

**Comment by davidg-unity** [comment]
Fixed by pull request #22 
Merged to master
