### ISSUE TITLE
RemoveState has error in runtime

### ISSUE THREAD

**Issue by cjloh** [Unity-Technologies/SimpleAnimation#25]
i run this simple script to test the RemoveState but it return me this error
"Object reference not set to an instance of an object SimpleAnimationPlayable.UpdateStates" which point me to this line of code `float weight = hasAnyWeight ? state.weight / totalWeight : 0.0f;`

`
public string removeStateName;
void Update ()
{
if (Input.GetKeyDown (KeyCode.R)) 
{
		GetComponent<SimpleAnimation>().RemoveState (removeStateName);
}
}
`

**Comment by davidg-unity** [comment]
Thanks for reporting this issue.
A fix has been done for issue #30, which I believe is the same as this.
You can find the fix in Pull Request #31, which will soon be merged into master.
