### ISSUE TITLE
Not play animation in runtime

### ISSUE THREAD

**Issue by laicasaane** [Unity-Technologies/SimpleAnimation#39]
My project create this component by the following procedure:
1. Get all animation clips from either Animator or Animation component attached on the model.
2. Instantiate these clips.
3. If the animation clips gotten from Animation component are legacy, set `clip.legacy = false`.
4. If the component is Animator, get out the `animator.avatar` if there is any.
5. Call DestroyImmediate to destroy either the old Animator or Animation component.
6. Add SimpleAnimation component to the model.
7. Add all the animation clips to this component.
8. Call play with a specific state name.

The SimpleAnimation works well in Unity Editor, but it doesn't work in the release build. I've made some tests in runtime, the SimpleAnimation plus its states are created successfully. But somehow the animations doesn't run. I can get out the state name and length so there must be no problem with the animation clips.

I'm using Unity 2018.1 targeting .NET 4.x

**Comment by laicasaane** [comment]
I've had an answer for this problem already. It turns out that instantiating animation clips is redundant and I cannot convert legacy to mecanim at runtime (it only works in Editor). Thus I have figured out a solution for the problem. Please consider this issue as “closed”.

**Comment by bakhtiyar-ospanov** [comment]
Hi. What solution you came up with? Having the same issue

**Comment by laicasaane** [comment]
@bakhtiyar-ospanov Nothing we can do about this so I have had to resort to a simple wrapper. This is my code:
https://gist.github.com/laicasaane/c20529884236d8fc545ea4a0b39f3508
