### ISSUE TITLE
stopping queued animation leaves null state in anim list

### ISSUE THREAD

**Issue by robotink** [Unity-Technologies/SimpleAnimation#40]
to reproduce:
1) place 2 animations in the list, one "intro" called "Default" , one loop called "Default (1)"
2) after a few loops, Play() the intro, followed by PlayQueued("Default (1)", QueueMode.CompleteOthers)
3) call Stop();

in the 'if (mustUpdateWeights)' block on line 588 of SimpleAnimationPlayable.cs,
the m_States list now has a null state in slot 4, which was 
m_States[3].stateName = "Default (1)Queued Clone" in previous frames.

calling Stop("Default (1)") in step 3 does not cause the null ref

**Comment by davidg-unity** [comment]
Sorry for taking so long to answer you.

Null states in the array of states is expected, but the code should handle it gracefully. I fixed a few places where this was not the case, then I ran a test with the steps as described, and I didn't hit any null reference exceptions.

I'll close this for now. If you get issues after pulling [47eaf](https://github.com/Unity-Technologies/SimpleAnimation/commit/4e7af), please tell me.
