### ISSUE TITLE
Missed namespace TestTools Error

### ISSUE THREAD

**Issue by wolfand11** [Unity-Technologies/SimpleAnimation#47]
Assets/SimpleAnimationComponent/Tests/PlaymodeTests/ComparativeTests/BaseConditionsTests.cs(2,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?

open the project with unity 2018.2.5, appear the error message above.

**Comment by davidg-unity** [comment]
Fixed in #48, sorry for the long turnaround
