### ISSUE TITLE
SimpleAnimation on UI elements doesn't work

### ISSUE THREAD

**Issue by Viath** [Unity-Technologies/SimpleAnimation#54]
Hello, 

I've got a problem setting SimpleAnimation on UI elements.
I have a panel that I want to animate in the view when I press a key, but the animation doesn't seem to start even tho I use the Play() method. 

I tested on another gameObject (only a sprite this time) and it worked. 
Can you help me to find out why it's not working for UI elements ?

**Comment by davidg-unity** [comment]
Hey, can you file a Unity bug with an example of what you are doing (using the bug reporter)?

If you paste the bug number here after, I'll be able to open that project in a safe and confidential manner, and it'll be a lot easier to diagnose.

**Comment by Viath** [comment]
I was setting up a project with just my bug, but I think I managed to find the solution. The SimpleAnimation culling mode on the UI element was set to "Based on Renderers". I set it to always animate, and it now animate when I call the method Play().

I still have a problem tho, because Rewind seem to don't work on the UI and therefore I can't replay the animation. 

Here is the bug report number : 1137042

Thank you for your time.

**Comment by Viath** [comment]
The support answered me regarding my Rewind problem. Looks like I made a typo in the KeyCode calling the rewind method... Silly me !

Anyway, everything works fine now.
Just for reminder in case of someone encounters the same problem : set the culling mode to **Always animate** for the UI elements.

Again, thanks for you time. :)
