### ISSUE TITLE
The Playable is Null

### ISSUE THREAD

**Issue by BaldSavant** [Unity-Technologies/SimpleAnimation#57]
I'm getting a null reference error as I'm just trying to setup my scene. This is happening in Start as part of a whole process for setting up a heirarchy of playables and mixers.

```
ArgumentNullException: Value cannot be null.

Parameter name: The Playable is null.
UnityEngine.Playables.PlayableHandle.GetInputCount () <0x2102dd20560 + 0x00052> in <07acd42a4d064cbdac11856405cd71fb>:0
UnityEngine.Playables.PlayableExtensions.GetInputCount[U] (U playable) (at C:/buildslave/unity/build/Runtime/Export/Director/PlayableExtensions.cs:168)
SimpleAnimationPlayable.DoAddClip (System.String name, UnityEngine.AnimationClip clip) (at Assets/SimpleAnimationComponent/SimpleAnimationPlayable.cs:106)
SimpleAnimationPlayable.AddClip (UnityEngine.AnimationClip clip, System.String name) (at Assets/SimpleAnimationComponent/SimpleAnimationPlayable.cs:136)
PlayablesMecanim.<Start>g__AddClips|36_1 (System.Collections.Generic.List`1[T] theClips, SimpleAnimationPlayable theSAP) (at Assets/scripts/PlayablesMecanim.cs:150)
PlayablesMecanim.Start () (at Assets/scripts/PlayablesMecanim.cs:154)
```

This is the line of code that's causing the erorr:

`AddClips(wholeBody_Clips, wholeBody_SAP);`
`void AddClips(List<AnimationClip> theClips, SimpleAnimationPlayable theSAP)
        {
            theSAP.AddClip(theClips[0], theClips[0].name);
        }`

I'm referencing the SimpleAnimation.cs script for how to approach all of this and as far as I (or my lead) can tell, I seem to be doing everything the same way. Are we simply missing something?

Your help is appreciated either way.

**Comment by davidg-unity** [comment]
Can you show me how your SimpleAnimationPlayable is created?

**Comment by BaldSavant** [comment]
Sure thing, the playable is made just before the AddClips call using the following lines:

`createPlayables(wholeBody_Playable, wholeBody_Mixer);


void createPlayables(ScriptPlayable<SimpleAnimationPlayable> thePlayable, AnimationLayerMixerPlayable theMixer)
        {
            var loopPlayable = new SimpleAnimationPlayable();
            thePlayable = ScriptPlayable<SimpleAnimationPlayable>.Create(theGraph, loopPlayable, 1);
        }
`

**Comment by davidg-unity** [comment]
I think it should be `void createPlayables(ref ScriptPlayable<SimpleAnimationPlayable> thePlayable, AnimationLayerMixerPlayable theMixer)`

ScriptPlayable is a struct, so it gets copied when passing it in a function

**Comment by BaldSavant** [comment]
Wow. Yep. It really was just that. Thanks for spotting that, I'm embarrassed to have gone to a forum for such a simple error!
